// Write a java program to demonastrate exception handling using try and catch.
import java.util.Scanner;

public class Exception_handling
{
    public static void main(String args[])
    {
     System.out.println("Enter any two numbers :");
     Scanner sc = new Scanner(System.in);
     try {
     int a = sc.nextInt();
     int b = sc.nextInt();
     int c = a/b;
     System.out.println("The answer is :" + " " + c);     
    }
    catch(ArithmeticException e) {
        System.out.println("Division by zero" + e);
    }
}
}
